#!/bin/bash 
REVERSE=0
func(){
	if [ $REVERSE -eq 0 ]; then
		echo "$PWD"
	fi
	for i in `ls`; do
 		if [[ -d $i ]]; then
		  cd ./$i
		  func $i
		  cd ..
		fi
	done
	if [ $REVERSE -eq 1 ]; then
		echo "$PWD"
	fi
}

if [[ $1 = '-?' ]]; then
	echo "	2016 MAI No.8 
Recursively specified directory and
display the full paths of subdirectories
./lab21 <DIR>
	Flags:
		-r reverse 
		" 
	shift
	if [[ $# -eq 0 ]]; then
	 exit 
	fi
fi

if [[ $1 = '-r' ]]; then
	echo "Reverse mod activatade" 
	REVERSE=1
	shift
fi

if [ $# -gt 1 ] ; then 
	echo "Please enter one dir
Thanks" 
	read a
  	if [ -d a ]; then 
		cd ./$a
		func
	else
		echo "Its not a dir 
Next you, lucky, will be.  Yes, hmmm.
How to use my script:
./lab21 <DIR>
	Flags:
	-r reverse "
	exit
	fi
elif [ $# -eq 0 ]; then 
    func
else 
    if [ -d $1 ]; then 
        cd ./$1
        func 
    else
    echo "Its not a dir 
Next you, lucky, will be.  Yes, hmmm.
How to use my script:
./lab21 <DIR>
	Flags:
	-r reverse "
    fi
fi
